"""add email and phone to users

Revision ID: f4fde3851b86
Revises: 1dc8c2ca36fe
Create Date: 2026-08-26 17:48:40.401028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fde3851b86'
down_revision = '1dc8c2ca36fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:

        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
